# Problem 1 

In [11]:
# 1 - numpy kütüphanesini import edin
import numpy as np

# 2 - 5 elemanlı bir numpy array oluşturun
a = np.random.rand(5)
print(a)

# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
a.sort()
print(a)


[0.62499684 0.43663107 0.40960628 0.13989849 0.26303013]
[0.13989849 0.26303013 0.40960628 0.43663107 0.62499684]


# Problem 2

In [46]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
import numpy as np

a = np.array([10,15,30,45,60])
print(a)

# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
b = np.arange(5,15)
print(b)

# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
c = np.arange(50,100,5)
print(c)

# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
np.zeros(10)

# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
d = np.ones(10)
print(d)

# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
e = np.linspace(0,100,5)
print(e)

# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
x = np.random.randint(10,30,5)
print(x)

# 8- [-1 ile 1] arasında 10 adet sayı üretin.
y = np.random.uniform(-1, 1, 10)
print(y)

# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
y = np.random.randint(10,50,size = (3,5))
print(y)

# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
print(y.sum(axis = 1))
print(y.sum(axis = 0))

# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
max = np.max(y)
min = np.min(y)
ort = np.mean(y)
print(max)
print(min)
print(ort)

# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
max_index = np.where(y == np.max(y))
print("En büyük değerin indeksi:", max_index)

# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
a = np.arange(10,20)
print(a)
print(a[0:3])

# 14- Üretilen dizinin elemanlarını tersten yazdırın.
print(a[::-1])

# 15- Üretilen matrisin ilk satırını seçiniz.
print(y[0, :])

# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
print(y[1, 2])

# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
print(y[:, 0])

# 18- Üretilen matrisin her bir elemanının karesini alınız.
karesi = y**2
print(karesi)
# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
cift_sayilar = y[y%2==0]
print(cift_sayilar)


[10 15 30 45 60]
[ 5  6  7  8  9 10 11 12 13 14]
[50 55 60 65 70 75 80 85 90 95]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[  0.  25.  50.  75. 100.]
[20 27 19 18 24]
[-0.883054   -0.31411294 -0.48228974  0.78513035 -0.83839045 -0.40957717
  0.60224953 -0.40458097 -0.90582561 -0.22102655]
[[15 49 38 49 26]
 [46 23 46 37 39]
 [45 48 39 46 40]]
[177 191 218]
[106 120 123 132 105]
49
15
39.06666666666667
En büyük değerin indeksi: (array([0, 0], dtype=int64), array([1, 3], dtype=int64))
[10 11 12 13 14 15 16 17 18 19]
[10 11 12]
[19 18 17 16 15 14 13 12 11 10]
[15 49 38 49 26]
46
[15 46 45]
[[ 225 2401 1444 2401  676]
 [2116  529 2116 1369 1521]
 [2025 2304 1521 2116 1600]]
[38 26 46 46 48 46 40]
