# Problem 1

In [11]:
# 1 - numpy kütüphanesini import edin
import numpy as np
# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin
a = np.random.randint(2,10,9)
print(a)
# 3 - matris'in boyutunu öğrenin
print(a.ndim)
# 4 - matris'i yeniden boyutlandırın
b= a.reshape(3,3)
print(b)
# 5 - matris'in boyut sayısını öğrenin
print(b.ndim)

[2 3 9 9 2 5 3 6 9]
1
[[2 3 9]
 [9 2 5]
 [3 6 9]]
2


# Problem 2

In [23]:
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin
import numpy as np
a = np.arange(1,10,2)
print(a)

# 2 - Oluşturduğunuz matrisi parçalayın
split_arrays = (np.split(a,[2,5]))
print(split_arrays)

# 3 - Parçalanmış matrisleri birleştirin
combine_array = np.concatenate(split_arrays)
print(combine_array)



[1 3 5 7 9]
[array([1, 3]), array([5, 7, 9]), array([], dtype=int32)]
[1 3 5 7 9]


# Problem 3

In [35]:
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin
x = np.random.choice(np.arange(5,100,2),10, replace=False)
print(x)

# 2 - matris'in özelliklerini inceleyin

print(x.ndim)
print(x.size)
print(a.dtype)


[95 27 77 87 45 19 93 33 11 53]
1
10
int32
